### PR TITLE
Implement the Protoc builder

### PR DESCRIPTION
**Pull request by brgirgis**

### CODE REVIEW

**Comment by bdbaddog** [comment]
Looks good. MIT License right?

**Comment by brgirgis** [comment]
MIT is fine by me. I need to reference others as well from whom I got some ideas. @petriborg @shaywood

**Comment by shaywood** [comment]
It's been years since I even touched this code- I'm more than happy for anything I might have contributed to be licensed under MIT and contributed to the project. :)

**Comment by bdbaddog** [comment]
Merged! Thanks!

**Comment by petriborg** [comment]
I'm like wise happy with MIT.

**Pull request merged**
